apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jpm3q58gt-python 
  janus-idp.io/tekton: jpm3q58gt-python
  backstage.io/kubernetes-id: jpm3q58gt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jpm3q58gt-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml